config/routes.rb
Rails.application.routes.draw do
  get 'top/main'
  root 'top#main'
  resources :products
  resources :cartitems, only: [:create, :destroy]
  resources :carts, only: [:show]
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cartitems
end

app/models/cartitem.rb
class Cartitem < ActiveRecord::Base
  belongs_to :carts
  has_one :products, dependent: :destroy
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_one :cartitems, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private
  def current_cart
    if session[:cart_id]
      cart = Cart.find(session[:cart_id])
    else
      cart = Cart.create
      session[:cart_id] = cart.id
    end
    cart
  end
  helper_method :current_cart
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cartitems_controller.rb
class CartitemsController < ApplicationController
  def create
    @product = Product.find(params[:product_id])
    @cartitem = Cartitem.new(qty: 1, product_id: @product.id, cart_id: params[:cart_id])
    @cartitem.save
    redirect_to top_main_path
  end

  def destroy
    Cartitem.find(params[:id]).delete
    redirect_to top_main_path
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cartitem = Cartitem.all
    @product = Product.all
    @pricesum = 0
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @product = Product.all
  end

  def new
    @product = Product.new
    @cartitem = Cartitem.new
  end

  def create
    @product = Product.new(name: params[:product][:name], price: params[:product][:price])
    @product.save
    redirect_to top_main_path
  end

  def destroy
    if Cartitem.find_by(product_id: params[:id])
      Cartitem.find_by(product_id: params[:id]).delete
    end
    Product.find(params[:id]).delete
    redirect_to top_main_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    @product = Product.all
    @cartitem = Cartitem.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/carts/show.html.erb
<p>
  <% @cartitem.each do |item| %>
  <% @product = Product.find(item.product_id) %>
   商品名:<%= @product.name%>
   価格:<%= @product.price %>円
   数量:<%= item.qty %>個
   <%= link_to "カートから削除", cartitem_path(id: item.id), method: :delete %>
   <% @pricesum = @pricesum + @product.price * item.qty %>
   <br>
  <% end %>
</p>

<p>合計金額:<%= @pricesum %>円</p>

<p><%= link_to "ホームに戻る", top_main_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<p>
<% @product.each do |item| %>
商品名:<%= item.name %>
価格:<%= item.price %>円
<%= link_to '削除', product_path(item.id), method: :delete, data: { confirm: '削除していいですか？' } %>
<br>
<% end %>
</p>

<p><%= link_to "ホームに戻る", top_main_path %></p>

app/views/products/new.html.erb
<%= form_for @product , url:{action: :create} do |f| %>
  <%= f.label :name,'商品名' %>
  <%= f.text_field :name %>
  <%= f.label :price,'価格' %>
  <%= f.number_field :price %>円
 <p><%= f.submit '登録' %></p>
<% end %>

app/views/top/main.html.erb
<%= link_to "品物を登録", new_product_path %>

<%= link_to "品物一覧", products_path %>

<%= link_to "カート一覧", cart_path(:cart_id) %>

<p>
<% @product.each do |item| %>
商品名:<%= item.name %>
価格:<%= item.price %>円
<%= link_to 'カートに追加', cartitems_path(product_id: item.id, cart_id: :cart_id), method: :create %>
<br>
<% end %>
</p>